version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: f1mexicorn-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: f1_application
      MYSQL_USER: f1mexicorndev
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: f1mexicorn-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    name: f1mexicorn-network