/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  GetRacesF1SessionsGetParams,
  GetSessionDriversF1SessionDriversGetParams,
  GetSessionStandingF1SessionStandingGetParams,
  GetUserGuessF1GuessEventIdGet200,
  GetWinnersResultsWinnersGet200,
  GetWinnersResultsWinnersGetParams,
  GoogleAuthorizationToken,
  Guess,
  HTTPValidationError,
  Race,
  RaceDriver,
  Standings,
  UserInfo,
} from '.././model';

/**
 * @summary Google Auth
 */
export const googleAuthUsersAuthGooglePost = (
  googleAuthorizationToken: GoogleAuthorizationToken,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserInfo>> => {
  return axios.post(`/users/auth/google`, googleAuthorizationToken, options);
};

export const getGoogleAuthUsersAuthGooglePostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>,
    TError,
    { data: GoogleAuthorizationToken },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>,
  TError,
  { data: GoogleAuthorizationToken },
  TContext
> => {
  const mutationKey = ['googleAuthUsersAuthGooglePost'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>,
    { data: GoogleAuthorizationToken }
  > = (props) => {
    const { data } = props ?? {};

    return googleAuthUsersAuthGooglePost(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoogleAuthUsersAuthGooglePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>
>;
export type GoogleAuthUsersAuthGooglePostMutationBody = GoogleAuthorizationToken;
export type GoogleAuthUsersAuthGooglePostMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Google Auth
 */
export const useGoogleAuthUsersAuthGooglePost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>,
      TError,
      { data: GoogleAuthorizationToken },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof googleAuthUsersAuthGooglePost>>,
  TError,
  { data: GoogleAuthorizationToken },
  TContext
> => {
  const mutationOptions = getGoogleAuthUsersAuthGooglePostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get Races
 */
export const getRacesF1SessionsGet = (
  params?: GetRacesF1SessionsGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Race[]>> => {
  return axios.get(`/f1/sessions`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetRacesF1SessionsGetQueryKey = (params?: GetRacesF1SessionsGetParams) => {
  return [`/f1/sessions`, ...(params ? [params] : [])] as const;
};

export const getGetRacesF1SessionsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetRacesF1SessionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRacesF1SessionsGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRacesF1SessionsGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRacesF1SessionsGet>>> = ({ signal }) =>
    getRacesF1SessionsGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRacesF1SessionsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRacesF1SessionsGet>>
>;
export type GetRacesF1SessionsGetQueryError = AxiosError<HTTPValidationError>;

export function useGetRacesF1SessionsGet<
  TData = Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: undefined | GetRacesF1SessionsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRacesF1SessionsGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRacesF1SessionsGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRacesF1SessionsGet<
  TData = Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetRacesF1SessionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRacesF1SessionsGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRacesF1SessionsGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRacesF1SessionsGet<
  TData = Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetRacesF1SessionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRacesF1SessionsGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Races
 */

export function useGetRacesF1SessionsGet<
  TData = Awaited<ReturnType<typeof getRacesF1SessionsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetRacesF1SessionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRacesF1SessionsGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRacesF1SessionsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Session Drivers
 */
export const getSessionDriversF1SessionDriversGet = (
  params: GetSessionDriversF1SessionDriversGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RaceDriver[]>> => {
  return axios.get(`/f1/session_drivers`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetSessionDriversF1SessionDriversGetQueryKey = (
  params?: GetSessionDriversF1SessionDriversGetParams,
) => {
  return [`/f1/session_drivers`, ...(params ? [params] : [])] as const;
};

export const getGetSessionDriversF1SessionDriversGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetSessionDriversF1SessionDriversGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSessionDriversF1SessionDriversGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>
  > = ({ signal }) => getSessionDriversF1SessionDriversGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionDriversF1SessionDriversGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>
>;
export type GetSessionDriversF1SessionDriversGetQueryError = AxiosError<HTTPValidationError>;

export function useGetSessionDriversF1SessionDriversGet<
  TData = Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetSessionDriversF1SessionDriversGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionDriversF1SessionDriversGet<
  TData = Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetSessionDriversF1SessionDriversGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionDriversF1SessionDriversGet<
  TData = Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetSessionDriversF1SessionDriversGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Session Drivers
 */

export function useGetSessionDriversF1SessionDriversGet<
  TData = Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetSessionDriversF1SessionDriversGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionDriversF1SessionDriversGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSessionDriversF1SessionDriversGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get User Guess
 */
export const getUserGuessF1GuessEventIdGet = (
  eventId: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetUserGuessF1GuessEventIdGet200>> => {
  return axios.get(`/f1/guess/${eventId}`, options);
};

export const getGetUserGuessF1GuessEventIdGetQueryKey = (eventId?: number) => {
  return [`/f1/guess/${eventId}`] as const;
};

export const getGetUserGuessF1GuessEventIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserGuessF1GuessEventIdGetQueryKey(eventId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>> = ({
    signal,
  }) => getUserGuessF1GuessEventIdGet(eventId, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!eventId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserGuessF1GuessEventIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>
>;
export type GetUserGuessF1GuessEventIdGetQueryError = AxiosError<HTTPValidationError>;

export function useGetUserGuessF1GuessEventIdGet<
  TData = Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  eventId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserGuessF1GuessEventIdGet<
  TData = Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserGuessF1GuessEventIdGet<
  TData = Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get User Guess
 */

export function useGetUserGuessF1GuessEventIdGet<
  TData = Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGuessF1GuessEventIdGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserGuessF1GuessEventIdGetQueryOptions(eventId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Post User Guess
 */
export const postUserGuessF1GuessPost = (
  guess: Guess,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Guess>> => {
  return axios.post(`/f1/guess`, guess, options);
};

export const getPostUserGuessF1GuessPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUserGuessF1GuessPost>>,
    TError,
    { data: Guess },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUserGuessF1GuessPost>>,
  TError,
  { data: Guess },
  TContext
> => {
  const mutationKey = ['postUserGuessF1GuessPost'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUserGuessF1GuessPost>>,
    { data: Guess }
  > = (props) => {
    const { data } = props ?? {};

    return postUserGuessF1GuessPost(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUserGuessF1GuessPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUserGuessF1GuessPost>>
>;
export type PostUserGuessF1GuessPostMutationBody = Guess;
export type PostUserGuessF1GuessPostMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Post User Guess
 */
export const usePostUserGuessF1GuessPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUserGuessF1GuessPost>>,
      TError,
      { data: Guess },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUserGuessF1GuessPost>>,
  TError,
  { data: Guess },
  TContext
> => {
  const mutationOptions = getPostUserGuessF1GuessPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get Session Standing
 */
export const getSessionStandingF1SessionStandingGet = (
  params?: GetSessionStandingF1SessionStandingGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Standings>> => {
  return axios.get(`/f1/session_standing`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetSessionStandingF1SessionStandingGetQueryKey = (
  params?: GetSessionStandingF1SessionStandingGetParams,
) => {
  return [`/f1/session_standing`, ...(params ? [params] : [])] as const;
};

export const getGetSessionStandingF1SessionStandingGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetSessionStandingF1SessionStandingGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSessionStandingF1SessionStandingGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>
  > = ({ signal }) => getSessionStandingF1SessionStandingGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionStandingF1SessionStandingGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>
>;
export type GetSessionStandingF1SessionStandingGetQueryError = AxiosError<HTTPValidationError>;

export function useGetSessionStandingF1SessionStandingGet<
  TData = Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: undefined | GetSessionStandingF1SessionStandingGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionStandingF1SessionStandingGet<
  TData = Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetSessionStandingF1SessionStandingGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionStandingF1SessionStandingGet<
  TData = Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetSessionStandingF1SessionStandingGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Session Standing
 */

export function useGetSessionStandingF1SessionStandingGet<
  TData = Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetSessionStandingF1SessionStandingGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingF1SessionStandingGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSessionStandingF1SessionStandingGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Session Standing Sse
 */
export const getSessionStandingSseF1SessionStandingSseGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`/f1/session_standing_sse`, options);
};

export const getGetSessionStandingSseF1SessionStandingSseGetQueryKey = () => {
  return [`/f1/session_standing_sse`] as const;
};

export const getGetSessionStandingSseF1SessionStandingSseGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSessionStandingSseF1SessionStandingSseGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>
  > = ({ signal }) => getSessionStandingSseF1SessionStandingSseGet({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionStandingSseF1SessionStandingSseGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>
>;
export type GetSessionStandingSseF1SessionStandingSseGetQueryError = AxiosError<unknown>;

export function useGetSessionStandingSseF1SessionStandingSseGet<
  TData = Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionStandingSseF1SessionStandingSseGet<
  TData = Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessionStandingSseF1SessionStandingSseGet<
  TData = Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Session Standing Sse
 */

export function useGetSessionStandingSseF1SessionStandingSseGet<
  TData = Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionStandingSseF1SessionStandingSseGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSessionStandingSseF1SessionStandingSseGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Winners
 */
export const getWinnersResultsWinnersGet = (
  params?: GetWinnersResultsWinnersGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetWinnersResultsWinnersGet200>> => {
  return axios.get(`/results/winners`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetWinnersResultsWinnersGetQueryKey = (
  params?: GetWinnersResultsWinnersGetParams,
) => {
  return [`/results/winners`, ...(params ? [params] : [])] as const;
};

export const getGetWinnersResultsWinnersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetWinnersResultsWinnersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWinnersResultsWinnersGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>> = ({
    signal,
  }) => getWinnersResultsWinnersGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWinnersResultsWinnersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>
>;
export type GetWinnersResultsWinnersGetQueryError = AxiosError<HTTPValidationError>;

export function useGetWinnersResultsWinnersGet<
  TData = Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: undefined | GetWinnersResultsWinnersGetParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
          TError,
          Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWinnersResultsWinnersGet<
  TData = Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetWinnersResultsWinnersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
          TError,
          Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWinnersResultsWinnersGet<
  TData = Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetWinnersResultsWinnersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Winners
 */

export function useGetWinnersResultsWinnersGet<
  TData = Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetWinnersResultsWinnersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWinnersResultsWinnersGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWinnersResultsWinnersGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
