/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */

export interface DriverPosition {
  position: number;
  driver_number: number;
  driver_name: string;
}
