/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */

export type GetRacesF1SessionsGetParams = {
  /**
   * Number of latest races to return, or all races if omitted
   */
  limit?: number | null;
};
