/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */

export type GetSessionStandingF1SessionStandingGetParams = {
  /**
   * Session key of the requested results
   */
  session_key?: number;
};
