/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { Guess } from './guess';

export type GetWinnersResultsWinnersGet200 = Guess | null;
