/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { GuessGuessId } from './guessGuessId';
import type { GuessUserId } from './guessUserId';

export interface Guess {
  guess_id?: GuessGuessId;
  user_id?: GuessUserId;
  race_id: number;
  position_1_driver_id: number;
  position_2_driver_id: number;
  position_3_driver_id: number;
}
