/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { RaceDriverRaceDriverId } from './raceDriverRaceDriverId';

export interface RaceDriver {
  race_driver_id?: RaceDriverRaceDriverId;
  race_id: number;
  driver_number: number;
  /** @maxLength 100 */
  driver_name: string;
  /** @maxLength 50 */
  nationality: string;
  /** @maxLength 50 */
  team: string;
}
