/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { RaceRaceId } from './raceRaceId';

export interface Race {
  race_id?: RaceRaceId;
  /** @maxLength 100 */
  race_name: string;
  /** @maxLength 100 */
  race_type: string;
  race_date: string;
}
