/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfoAccessToken } from './userInfoAccessToken';

export interface UserInfo {
  email: string;
  name: string;
  access_token: UserInfoAccessToken;
}
