/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { AccessToken } from './accessToken';

export type UserInfoAccessToken = AccessToken | null;
