/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * F1 Mexicorn
 * OpenAPI spec version: 0.1.0
 */
import type { UserUserId } from './userUserId';

export interface User {
  /** @maxLength 100 */
  email: string;
  user_id?: UserUserId;
  /** @maxLength 50 */
  username: string;
}
